name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Wybierz odpowiednią wersję Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run predeploy

      - name: List files in dist folder
        run: ls -R dist/smart-guys-app

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/smart-guys-app/browser --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Używa automatycznego tokenu
