name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # permits writing into repository
      pages: write      # permissions for GitHub Pages
      id-token: write   # needed for publication 

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Choose Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run predeploy

      - name: List files in dist folder
        run: ls -R dist/smart-guys-app
        
      - name: Configure Git
        run: |
          git config --global user.email "80596881+Inen89@users.noreply.github.com"
          git config --global user.name "Inen89"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses automatic token
